<?php
/**
 * questions_data.php — Dados das questões (arrays puros)
 * 
 * Separado do migrate.php para permitir reuso por múltiplos scripts
 * (migrate.php, recriar_questoes.php, etc.) sem executar lógica de banco.
 * 
 * Define: $questoesModulo1 ... $questoesModulo10
 * Cada array contém tuplas: [dificuldade, texto, opcao_a, opcao_b, opcao_c, opcao_d, resposta]
 */

$questoesModulo1 = [
    ["Fácil","Qual teórica da enfermagem desenvolveu a Teoria das Necessidades Humanas Básicas?","Florence Nightingale","Wanda de Aguiar Horta","Jean Watson","Madeleine Leininger","B"],
    ["Fácil","Segundo Wanda Horta, as necessidades humanas básicas são divididas em quantos níveis?","Dois","Três","Quatro","Cinco","B"],
    ["Fácil","O nível psicobiológico inclui necessidades de:","Oxigenação, nutrição, sono","Autoestima, lazer","Religiosidade, transcendência","Comunicação, afeto","A"],
    ["Fácil","A necessidade de autoestima pertence a qual nível?","Psicobiológico","Psicossocial","Psicoespiritual","Biológico","B"],
    ["Fácil","Necessidades psicoespirituais referem-se a:","Crenças e valores","Funções orgânicas","Interação social","Atividades físicas","A"],
    ["Fácil","Paciente com dispneia tem necessidade prioritária em:","Oxigenação (psicobiológica)","Autoestima","Lazer","Transcendência","A"],
    ["Fácil","A teoria de Horta foi influenciada por qual psicólogo?","Freud","Maslow","Piaget","Pavlov","B"],
    ["Fácil","Para Horta, o ser humano é:","Integral com múltiplas dimensões","Exclusivamente biológico","Apenas social","Apenas espiritual","A"],
    ["Fácil","A teoria de Horta é aplicada através da:","SAE","Prescrição médica","Administração","Farmácia","A"],
    ["Fácil","Úlcera por pressão afeta qual necessidade?","Integridade cutânea (psicobiológica)","Nutrição","Lazer","Comunicação","A"],
    ["Fácil","Medo da cirurgia afeta necessidade de:","Segurança emocional (psicossocial)","Oxigenação","Eliminação","Sono","A"],
    ["Fácil","A necessidade de privacidade é:","Psicossocial","Psicobiológica","Psicoespiritual","Fisiológica","A"],
    ["Fácil","Wanda Horta defendia que a enfermagem é:","Uma ciência","Um ofício","Uma técnica","Uma arte","A"],
    ["Fácil","Visão holística na enfermagem significa:","Ver o paciente como um todo integral","Focar apenas na doença","Ignorar emoções","Padronizar cuidados","A"],
    ["Fácil","São necessidades psicossociais, EXCETO:","Oxigenação","Comunicação","Lazer","Segurança emocional","A"],
    ["Fácil","Paciente com insônia tem necessidade de:","Sono e repouso","Nutrição","Eliminação","Locomoção","A"],
    ["Fácil","A necessidade de dignidade está em qual nível?","Psicossocial","Psicobiológico","Psicoespiritual","Físico","A"],
    ["Fácil","A teoria de Horta é considerada de:","Média abrangência","Baixa abrangência","Alta abrangência","Microteoria","A"],
    ["Fácil","A necessidade de transcendência é:","Psicoespiritual","Psicobiológica","Psicossocial","Fisiológica","A"],
    ["Fácil","Wanda Horta nasceu em qual estado?","Paraná","São Paulo","Rio de Janeiro","Minas Gerais","A"],
    ["Fácil","O desequilíbrio das necessidades básicas pode levar:","Ao processo saúde-doença","Só a doenças físicas","Só a problemas psicológicos","Só a problemas sociais","A"],
    ["Fácil","Horta revolucionou a enfermagem ao:","Criar método científico para a prática","Enfatizar o cuidado técnico","Valorizar a intuição","Substituir a medicina","A"],
    ["Fácil","Paciente que não pode andar precisa de ajuda para:","Locomoção (psicobiológica)","Comunicação","Transcendência","Lazer","A"],
    ["Fácil","A teoria de Horta humaniza a enfermagem ao:","Considerar o paciente como ser único e integral","Ignorar sentimentos","Focar na doença","Padronizar cuidados","A"],
    ["Fácil","O processo saúde-doença para Horta deve-se a:","Desequilíbrio das necessidades","Só fatores biológicos","Só fatores socioeconômicos","Só ambientais","A"],
    ["Fácil","O ser humano para Horta é:","Ativo e participante do cuidado","Passivo","Totalmente dependente","Sem autonomia","A"],
    ["Fácil","Horta valoriza o conhecimento:","Científico e sistematizado","Intuitivo e empírico","Só tradicional","Só popular","A"],
    ["Fácil","A teoria de Horta se alinha a qual princípio do SUS?","Integralidade","Regionalização","Hierarquização","Descentralização","A"],
    ["Fácil","A necessidade de cuidado corporal é:","Psicobiológica","Psicossocial","Psicoespiritual","Estética","A"],
    ["Fácil","Para Horta, o cuidado sem método científico é:","Apenas uma ocupação","Arte","Ciência","Técnica","A"],
    ["Fácil","A avaliação das necessidades deve ser:","Contínua durante todo cuidado","Só na admissão","Só na alta","Só pelo médico","A"],
    ["Fácil","O principal objetivo da teoria de Horta é:","Organizar o cuidado humano integral","Classificar doenças","Substituir outras teorias","Padronizar medicamentos","A"],
    ["Fácil","A necessidade de 'aceitação' é:","Psicossocial","Psicobiológica","Psicoespiritual","Biológica","A"],
    ["Fácil","Para aplicar a teoria de Horta, o enfermeiro usa:","O processo de enfermagem","Apenas o exame físico","Apenas a entrevista","A prescrição médica","A"],
    ["Fácil","O modelo biomédico difere de Horta por:","Fragmentar o ser humano","Considerar o paciente como um todo","Valorizar necessidades psicossociais","Incluir espiritualidade","A"],
    ["Fácil","Para Horta, o cuidado de enfermagem deve ser:","Contínuo e planejado","Pontual e reativo","Só curativo","Só preventivo","A"],
    ["Fácil","A necessidade de 'integridade cutânea' é:","Psicobiológica","Psicossocial","Psicoespiritual","Estética","A"],
    ["Fácil","Aplicar Horta requer do enfermeiro:","Raciocínio clínico e julgamento crítico","Só habilidades técnicas","Só conhecimento farmacológico","Só empatia","A"],
    ["Fácil","A necessidade de espiritualidade está presente em:","Todos os seres humanos","Só pacientes religiosos","Só pacientes terminais","Só idosos","A"],
    ["Fácil","A necessidade de 'comunicação' é essencialmente:","Psicossocial","Biológica","Física","Psicoespiritual","A"],
    ["Fácil","Para Horta, o enfermeiro deve considerar:","Todas as dimensões do ser humano","Só a doença","Só os sintomas","Só os exames","A"],
    ["Fácil","A necessidade mais imediata para a sobrevivência é:","Oxigenação","Lazer","Autoestima","Transcendência","A"],
    ["Fácil","O paciente tem direito a ter suas crenças respeitadas. Isso se refere a:","Necessidades psicoespirituais","Necessidades psicobiológicas","Necessidades psicossociais","Ética médica","A"],
    ["Fácil","A teoria de Horta é essencial para:","Fundamentar o diagnóstico de enfermagem","Substituir o exame físico","Eliminar a anotação","Reduzir a equipe","A"],
    ["Fácil","A abordagem integral proposta por Horta representa:","Um avanço na qualidade do cuidado","Um retrocesso","Uma dificuldade","Apenas teoria sem aplicação","A"],
    ["Fácil","A visão de Horta sobre o ser humano é:","Holística","Cartesiana","Fragmentada","Biomédica","A"],
    ["Fácil","Horta contribuiu para a autonomia do enfermeiro ao:","Fundamentar cientificamente as decisões","Submeter ao médico","Eliminar diagnósticos","Reduzir responsabilidades","A"],
    ["Fácil","A necessidade de 'esperança' está relacionada a:","Necessidades psicoespirituais","Necessidades psicobiológicas","Necessidades psicossociais","Necessidades fisiológicas","A"],
    ["Médio","Paciente desnutrido, deprimido e sem visitas. Quantos níveis de necessidade estão afetados?","Três: psicobiológico+psicossocial+psicoespiritual","Só psicobiológico","Psicobiológico e psicossocial","Nenhum","A"],
    ["Médio","Para priorizar cuidados, Horta orienta:","Hierarquizar necessidades, priorizando urgentes","Atender por ordem de chegada","Só pacientes graves","Só seguir prescrição","A"],
    ["Médio","Recusa alimentar por crença religiosa: conflito entre:","Psicobiológica e psicoespiritual","Psicossocial e psicobiológica","Psicossocial e psicoespiritual","Nenhum","A"],
    ["Médio","Idoso acamado com escaras e abandono familiar requer:","Cuidado integral: pele+nutrição+afeto+social","Só curativos","Só psicólogo","Institucionalização","A"],
    ["Médio","A necessidade de esperança é:","Psicoespiritual","Psicobiológica","Psicossocial","Fisiológica","A"],
    ["Médio","Visão integral de Horta é chamada de:","Holística","Biomédica","Cartesiana","Fragmentada","A"],
    ["Médio","O nível psicoespiritual inclui necessidades de:","Transcendência, valores e crenças","Alimentação/hidratação","Socialização/lazer","Locomoção","A"],
    ["Médio","Wanda Horta foi influenciada pela teoria:","Ambientalista de Nightingale","do Autocuidado de Orem","da Adaptação de Roy","do Cuidado Transpessoal","A"],
    ["Médio","Multiplas necessidades: o enfermeiro deve:","Hierarquizar e priorizar urgentes","Tratar a mais fácil","Ignorar as menos graves","Aguardar médico","A"],
    ["Médio","O enfermeiro que ignora necessidades psicoespirituais:","Presta cuidado incompleto","Presta cuidado integral","Não comete falta","Melhora assistência","A"],
    ["Médio","O cuidado centrado no paciente significa:","Considerar necessidades individuais","Focar na doença","Padronizar o cuidado","Ignorar preferências","A"],
    ["Médio","Paciente com dor crônica tem principalmente afetada:","Conforto (psicobiológica)","Lazer","Transcendência","Comunicação","A"],
    ["Médio","Para identificar necessidades psicoespirituais, o enfermeiro deve:","Perguntar sobre valores e crenças","Ignorar crenças","Apenas observar","Delegar ao capelão","A"],
    ["Médio","Paciente com imobilidade no leito requer:","Prevenção de UPP e estímulo à mobilização","Só curativos","Só medicação","Transferência para UTI","A"],
    ["Médio","Horta contribui para autonomia do enfermeiro:","Fundamentando cientificamente suas ações","Subordinando ao médico","Eliminando registros","Reduzindo responsabilidades","A"],
    ["Médio","A necessidade de 'privacidade' é classificada como:","Psicossocial","Psicobiológica","Psicoespiritual","Fisiológica","A"],
    ["Médio","Paciente jovem com ansiedade generalizada. Qual nível mais afetado?","Psicossocial","Psicobiológico","Psicoespiritual","Nenhum","A"],
    ["Médio","O histórico de enfermagem deve identificar:","Necessidades afetadas em todos os níveis","Só problemas físicos","Só problemas psicológicos","Só dados administrativos","A"],
    ["Médio","A teoria de Horta se aplica:","Em todos os contextos da prática","Só em hospitais","Só em UTIs","Só na atenção básica","A"],
    ["Médio","Paciente com diabetes tem afetada necessidade de:","Regulação metabólica (psicobiológica)","Lazer","Transcendência","Interação social","A"],
    ["Médio","A Resolução COFEN que regulamenta a SAE é:","358/2009","240/2000","429/2012","564/2017","A"],
    ["Médio","Paciente em pós-operatório com dor intensa. Prioridade:","Conforto e alívio da dor","Lazer","Autoestima","Religiosidade","A"],
    ["Médio","Para identificar necessidades psicossociais, o enfermeiro deve:","Estabelecer vínculo e comunicação efetiva","Só observar","Só ler prontuário","Só perguntar à família","A"],
    ["Médio","A abordagem holística significa:","Considerar o paciente em todas as suas dimensões","Focar apenas na doença","Ignorar aspectos psicológicos","Tratar só sintomas","A"],
    ["Difícil","Paciente pós-operatório: dor 8/10, náuseas, medo, sem família. Prioridade:","Tratar dor (ameaça homeostase imediata)","Controlar náuseas","Apoio psicológico","Contactar família","A"],
    ["Difícil","Paciente terminal: dispneia+dor+isolamento+questionamento existencial. Abordagem:","Paliativa integral: física+social+espiritual","Só tratar dor/dispneia","Só capelania","Só assistência social","A"],
    ["Difícil","Queimado 40%, jejum, sedado, intubado, sem família. Hierarquia:","Oxigenação→pele→nutrição→suporte psicossocial","Só pele","Psicossocial primeiro","Nutrição primeiro","A"],
    ["Difícil","AVC: hemiplegia+afasia+disfagia+incontinência. Abordagem integral:","Comunicação+deglutição+mobilidade+eliminação+emocional","Só fisioterapia","Só fonoaudiologia","Só eliminação","A"],
    ["Difícil","Cetoacidose: confuso, glicemia 480. Prioridade:","Corrigir glicemia+hidratação+equilíbrio ácido-base","Orientar diabetes","Suporte psicológico","Contactar família","A"],
    ["Difícil","Ferida infectada: febril 39, taquicárdico, hipotenso. Sequência:","Estabilização→ATB→curativo","Curativo primeiro","Antitérmico","Só curativo","A"],
    ["Difícil","Cuidados paliativos: dispneia+dor+ansiedade+reconciliação. Abordagem:","Todas dimensões: física+social+espiritual","Só dor","Só reconciliação","Só dispneia","A"],
    ["Difícil","Obesidade+diabetes+úlcera+depressão. Níveis afetados:","Psicobiológico+psicossocial","Só psicobiológico","Só psicossocial","Nenhum","A"],
    ["Difícil","Maior contribuição de Wanda Horta para enfermagem:","Introduziu pensamento teórico e método científico","Criou a primeira escola","Descobriu cura de infecções","Criou Código de Ética","A"],
    ["Difícil","O método científico de Horta significa que o cuidado:","Foi sistematizado e baseado em evidências","Ficou subordinado à medicina","Perdeu o aspecto humano","Tornou-se exclusivamente técnico","A"],
    ["Difícil","Paciente com Alzheimer avançado. Prioridade:","Necessidades básicas: alimentação, hidratação, segurança","Estimulação cognitiva","Medicação","Contenção","A"],
    ["Difícil","Superlotação hospitalar: como aplicar Horta na priorização?","Hierarquizar: primeiro as psicobiológicas ameaçadas","Ordem de chegada","Só pacientes graves","Ignorar teoria na crise","A"],
    ["Difícil","Traqueostomado consciente que não pode falar. Necessidade urgente além da respiratória:","Comunicação (psicossocial)","Nutrição","Eliminação","Sono","A"],
    ["Difícil","Paciente com HIV: choro, isolamento, recusa alimentar. Análise:","Múltiplas necessidades: nutricional, interação, segurança emocional","Só nutrição","Só isolamento","Nenhuma intervenção","A"],
    ["Difícil","Idoso em situação de abandono: desnutrido, escaras, depressão. Abordagem:","Cuidado integral: nutrição, pele, afeto, inclusão social","Só desnutrição","Institucionalização imediata","Só notificar abandono","A"],
    ["Difícil","Paciente oncológico: mucosite, náuseas, perdeu 8kg, tristeza. Níveis afetados:","Psicobiológico+psicossocial+psicoespiritual","Só psicobiológico","Só psicossocial","Nenhum","A"],
    ["Difícil","Paciente que recusa alimentação por crença religiosa: conflito entre níveis:","Psicobiológico e psicoespiritual","Psicossocial e psicobiológico","Psicossocial e psicoespiritual","Nenhum","A"],
    ["Difícil","Fratura de fêmur+osteoporose+mora só+medo de cair. Diagnosticos:","Mobilidade+risco queda+medo+déficit autocuidado","Só mobilidade","Só risco queda","Só autocuidado","A"],
    ["Difícil","Pneumonia: diagnóstico de enfermagem prioritário:","Desobstrução ineficaz de vias aéreas","Pneumonia comunitária","Uso de antibióticos","Infecção pulmonar","A"],
    ["Difícil","Paciente com DPOC exacerbado: SpO2 85%, FR 32. Prioridade:","Troca gasosa prejudicada (risco de vida)","Ansiedade","Posicionamento","Medicação","A"],
    ["Difícil","Paciente séptico: PA 70×40, FC 120, FR 35. Diagnóstico mais urgente:","Débito cardíaco diminuído","Risco de infecção","Pele prejudicada","Mobilidade","A"],
    ["Difícil","Paciente em cuidados paliativos com dor refratária: abordagem:","Física+social+espiritual simultaneamente","Só controle da dor","Sedação","Transferência para UTI","A"],
    ["Difícil","Estomizado: planejamento de enfermagem deve considerar:","Eliminação+pele+autoimagem+interação social","Só eliminação","Só pele","Só autoimagem","A"],
    ["Difícil","Paciente com dispneia intensa+ansiedade+medo da morte. Prioridade imediata:","Oxigenoterapia e posicionamento","Ansiolítico","Psicólogo","Capelão","A"],
    ["Difícil","Paciente internado que não aceita alimentação por questões religiosas: como proceder?","Respeitar crenças + oferecer alternativas + registrar recusa","Obrigar alimentação por sonda","Ignorar a recusa","Só comunicar médico","A"],
    ["Difícil","Paciente pós-PCR: intubado, DVA, Glasgow 5, anúria 4h. Níveis afetados:","Psicobiológicos múltiplos e críticos","Só neurológico","Só cardíaco","Só renal","A"],
    ["Difícil","Diferencia entre o Modelo Biomédico e a Teoria de Horta:","Horta: visão integral; Biomédico: foco na doença","São iguais","Horta foca em exames","Biomédico é mais humano","A"],
    ["Difícil","Para Horta, o principal objetivo do enfermeiro é:","Atender as necessidades afetadas do ser humano","Curar doenças","Seguir ordens médicas","Administrar medicamentos","A"],
    ["Difícil","Paciente desnutrido tem cicatrização prejudicada por falta de:","Proteínas e vitaminas","Gordura","Carboidratos","Água","A"],
    ["Difícil","Paciente com úlcera venosa + depressão + isolamento social. Abordagem:","Cuidado integral: ferida+emoção+inserção social","Só tratar a ferida","Só antidepressivo","Só encaminhar para assistente social","A"],
];

$questoesModulo2 = [
    ["Fácil","A SAE é regulamentada pela Resolução COFEN:","358/2009","240/2000","429/2012","564/2017","A"],
    ["Fácil","Quantas etapas compõem a SAE?","5","3","4","6","A"],
    ["Fácil","A primeira etapa da SAE é:","Histórico de Enfermagem","Diagnóstico","Planejamento","Implementação","A"],
    ["Fácil","NANDA-I é a taxonomia para:","Diagnósticos de enfermagem","Intervenções","Resultados","Medicamentos","A"],
    ["Fácil","NIC é a classificação para:","Intervenções de enfermagem","Diagnósticos","Resultados","Sinais vitais","A"],
    ["Fácil","NOC é a classificação para:","Resultados de enfermagem","Diagnósticos","Intervenções","Procedimentos","A"],
    ["Fácil","A SAE é de competência:","Privativa do enfermeiro","Exclusiva do médico","Compartilhada","Do técnico","A"],
    ["Fácil","O mnemônico das etapas da SAE é:","HDPIA","ABCDE","HPDAI","APHID","A"],
    ["Fácil","Diagnóstico de enfermagem é:","Julgamento clínico sobre respostas humanas","Doença do paciente","Prescrição médica","Exame laboratorial","A"],
    ["Fácil","Implementação na SAE corresponde a:","Executar intervenções planejadas","Coletar dados","Definir diagnósticos","Avaliar resultados","A"],
    ["Fácil","O Histórico de Enfermagem inclui:","Entrevista e exame físico","Só exames","Só prescrição","Só sinais vitais","A"],
    ["Fácil","Avaliação na SAE serve para:","Verificar resultados alcançados","Iniciar processo","Coletar dados","Planejar","A"],
    ["Fácil","Sequência correta da SAE:","Histórico→Diagnóstico→Planejamento→Implementação→Avaliação","Diagnóstico→Histórico→Planejamento→Implementação→Avaliação","Planejamento→Histórico→Diagnóstico→Avaliação→Implementação","Histórico→Planejamento→Diagnóstico→Implementação→Avaliação","A"],
    ["Fácil","A SAE deve ser implementada:","Em toda unidade de saúde","Só em UTIs","Só em hospitais públicos","Só na atenção básica","A"],
    ["Fácil","O Planejamento na SAE define:","Resultados esperados e intervenções","Coleta de dados","Execução de procedimentos","Avaliação final","A"],
    ["Fácil","A SAE contribui para:","Organizar e qualificar a assistência","Só documentar","Aumentar burocracia","Reduzir contato com paciente","A"],
    ["Fácil","São etapas da SAE, EXCETO:","Prescrição Médica","Histórico","Diagnóstico","Avaliação","A"],
    ["Fácil","A SAE é obrigatória:","Em todo estabelecimento de saúde","Só em hospitais","Só em UTIs","Só em UBS","A"],
    ["Fácil","A SAE deve ser registrada:","No prontuário do paciente","Em folha avulsa","Só verbalmente","Em caderno","A"],
    ["Fácil","Para diagnósticos de enfermagem usa-se:","NANDA-I","CID-10","Classificação de medicamentos","Exames de imagem","A"],
    ["Fácil","A última etapa da SAE é:","Avaliação","Implementação","Planejamento","Diagnóstico","A"],
    ["Fácil","Comunicação na SAE é:","Fundamental para continuidade do cuidado","Desnecessária","Só para médicos","Opcional","A"],
    ["Fácil","A SAE é um processo:","Dinâmico e contínuo","Estático e linear","Só burocrático","Opcional","A"],
    ["Fácil","Avaliação de resultados deve ser:","Baseada em indicadores mensuráveis","Subjetiva","Ignorada","Só pelo médico","A"],
    ["Fácil","Diagnóstico 'Risco de infecção' é classificado como:","Risco","Bem-estar","Promoção da saúde","Síndrome","A"],
    ["Fácil","O histórico de enfermagem também é chamado de:","Coleta de dados","Evolução","Alta","Diagnóstico","A"],
    ["Fácil","A avaliação final da SAE permite:","Reiniciar processo se necessário","Encerrar caso definitivo","Ignorar resultados","Só arquivar","A"],
    ["Fácil","A SAE humaniza ao:","Valorizar respostas individuais","Padronizar todos","Ignorar queixas","Reduzir cuidado","A"],
    ["Fácil","O raciocínio clínico na SAE é essencial para:","Identificar diagnósticos precisos","Substituir o médico","Eliminar o exame físico","Reduzir a equipe","A"],
    ["Fácil","A SAE deve ser iniciada:","Na admissão do paciente","Após 24h","Só se solicitado","Na alta","A"],
    ["Médio","'Integridade tissular prejudicada' se refere a:","Lesão em tecidos profundos","Lesão na pele","Problema circulatório","Infecção","A"],
    ["Médio","Diagnóstico de enfermagem difere do médico por focar:","Na resposta humana aos problemas de saúde","Na doença","Nos exames","Nos medicamentos","A"],
    ["Médio","SAE promove segurança ao paciente ao:","Padronizar e sistematizar cuidados","Aumentar riscos","Ignorar protocolos","Reduzir equipe","A"],
    ["Médio","Pensamento crítico na SAE é necessário para:","Analisar dados e decidir com precisão","Aceitar tudo sem questionar","Ignorar evidências","Seguir intuição","A"],
    ["Médio","Para SAE com qualidade precisa-se de:","Conhecimento científico e raciocínio clínico","Só boa vontade","Só experiência","Só equipamentos","A"],
    ["Médio","Resultado NOC esperado para 'Dor aguda':","Nível de dor controlado","Piora da dor","Aumentar medicação","Imobilidade","A"],
    ["Médio","A SAE deve ser aplicada:","Em todos os níveis de atenção","Só em hospitais","Só em UTIs","Só na básica","A"],
    ["Médio","Etapa mais desafiadora da SAE:","Diagnóstico de enfermagem","Histórico","Implementação","Avaliação","A"],
    ["Médio","Para elaborar plano de cuidados precisa-se:","Dos diagnósticos e resultados esperados","Só da prescrição","Só dos exames","Só da queixa","A"],
    ["Médio","Registro preciso da SAE protege:","Paciente e profissional","Só o paciente","Só a instituição","Só o médico","A"],
    ["Difícil","AVC: hemiplegia+afasia+disfagia+choro. Diagnosticos:","Mobilidade+deglutição+comunicação+risco baixa autoestima","Só mobilidade","Só deglutição","Só comunicação","A"],
    ["Difícil","Diabético descompensado: glicemia 380, confuso. Sequência SAE:","Coletar→Diagnosticar→Planejar(insulina)→Implementar→Avaliar","Insulina→Coletar→Diagnosticar","Diagnosticar→Coletar","Avaliar→Insulina","A"],
    ["Difícil","DPOC exacerbado: SpO2 85%, FR 32, confuso. Prioridade SAE:","Histórico→Diagnóstico(troca gasosa)→Planejar(O2+posicionamento)","Ansiedade","Só posicionar","Só medicação","A"],
    ["Difícil","Diferença diagnóstico médico vs enfermagem:","Médico=foca doença; enfermagem=foca resposta humana","Não há diferença","Ambos focam doença","Enfermagem=foca exames","A"],
    ["Difícil","Pós-craniotomia: náuseas, cefaleia 9/10, fotofobia. Prioritário:","Risco de PIC aumentada - avaliação médica imediata","Náusea","Cefaleia","Ansiedade","A"],
    ["Difícil","Cateterismo cardíaco: hematoma inguinal, dor 7/10. Diagnosticos:","Risco perfusão ineficaz+dor aguda","Só dor","Só hematoma","Só ansiedade","A"],
    ["Difícil","Bronquiolite: SpO2 88%, FR 55, tiragem. Prioridade:","Troca gasosa prejudicada","Nutrição","Alimentação","Nebulização","A"],
    ["Difícil","Oncológico: mucosite 3°, náuseas, perdeu 8kg, tristeza. Diagnosticos:","Nutrição+mucosite+isolamento+tristeza","Só mucosite","Só tristeza","Só náuseas","A"],
    ["Difícil","Paciente com AVC hemorrágico: Glasgow 9, anisocoria. Prioridade:","Avaliação neurológica frequente e controle PIC","Só sinais vitais","Só decúbito","Só medicação","A"],
    ["Difícil","Paciente oncológico terminal: dor + náuseas + tristeza + reconciliação familiar. Abordagem SAE:","Todas as dimensões: física+emocional+espiritual+social","Só dor","Só emocional","Só espiritual","A"],
];

$questoesModulo3 = [
    ["Fácil","'Afebril' significa que o paciente:","Está sem febre","Tem febre alta","Febre intermitente","Hipotérmico","A"],
    ["Fácil","Normocárdico significa FC:","Normal 60-100 bpm","Acelerada","Lenta","Irregular","A"],
    ["Fácil","Eupneico significa FR:","Normal 16-20 irpm","Acelerada","Lenta","Ausente","A"],
    ["Fácil","Normotenso significa PA:","Normal 120×80 mmHg","Elevada","Reduzida","Instável","A"],
    ["Fácil","Anictérico indica que o paciente:","Não tem icterícia","Tem icterícia","Pele amarelada","Olhos amarelados","A"],
    ["Fácil","Normocorado significa:","Coloração normal da pele e mucosas","Palidez","Amarelado","Cianose","A"],
    ["Fácil","Lúcido e orientado significa:","Consciente e responde adequadamente","Inconsciente","Confuso","Sedado","A"],
    ["Fácil","'Diurese presente' indica:","Volume urinário normal","Ausência de urina","Dificuldade para urinar","Urina com sangue","A"],
    ["Fácil","São princípios da anotação, EXCETO:","Opinião pessoal","Objetividade","Clareza","Cronologia","A"],
    ["Fácil","Método SOAP é usado para:","Estruturar evolução de enfermagem","Calcular medicações","Classificar feridas","Fazer curativos","A"],
    ["Fácil","'S' no SOAP significa:","Subjetivo (queixa do paciente)","Sinais vitais","Sistematização","Solução","A"],
    ["Fácil","'O' no SOAP significa:","Objetivo (dados observados)","Organização","Orientação","Opinião","A"],
    ["Fácil","Bradicardia significa FC:","Lenta <60 bpm","Acelerada >100","Normal","Irregular","A"],
    ["Fácil","Taquipneico significa FR:","Acelerada >20 irpm","Normal","Lenta <12","Ausente","A"],
    ["Fácil","Anotação de enfermagem é documento:","Legal e ético","Informal","Descartável","Opcional","A"],
    ["Fácil","Cianose significa:","Coloração azulada/arroxeada","Pele rosada","Pele amarelada","Palidez","A"],
    ["Fácil","Disúria significa:","Dor ou dificuldade ao urinar","Ausência de urina","Urina em excesso","Normal","A"],
    ["Fácil","Anúria significa:","Ausência de produção de urina","Volume normal","Urina em excesso","Dor ao urinar","A"],
    ["Fácil","Hematêmese significa:","Vômito com sangue","Urina com sangue","Fezes com sangue","Tosse com sangue","A"],
    ["Fácil","Melena significa:","Fezes escuras com sangue digerido","Vômito com sangue","Urina escura","Tosse com sangue","A"],
    ["Fácil","Hemoptise significa:","Expectoração com sangue","Vômito com sangue","Fezes com sangue","Sangramento nasal","A"],
    ["Fácil","Na anotação, o enfermeiro registra:","O que observou, fez e a resposta do paciente","Só o que planeja","Só diagnóstico","Só SSVV","A"],
    ["Fácil","Assinatura na anotação deve conter:","Nome, categoria e número do conselho","Só nome","Só rubrica","Só cargo","A"],
    ["Fácil","Prontuário pertence:","Ao paciente","Ao médico","Ao hospital","Ao enfermeiro","A"],
    ["Fácil","Náusea significa:","Enjoo com vontade de vomitar","Vômito","Dor abdominal","Tontura","A"],
    ["Fácil","Poliúria significa volume:","Aumentado >2500 mL/dia","Diminuído","Ausente","Normal","A"],
    ["Fácil","A anotação deve ser feita:","Imediatamente após o procedimento","No final do plantão","1x/dia","Quando sobra tempo","A"],
    ["Fácil","'Hidratado' no exame físico significa:","Turgor e elasticidade normal da pele","Edema","Desidratado","Febril","A"],
    ["Fácil","Registro deve ser:","Legível e sem rasuras","Rasurado se erro","A lápis","Sem data","A"],
    ["Médio","Método SOAP foi criado por:","Lawrence Weed","Florence Nightingale","Wanda Horta","NANDA","A"],
    ["Médio","A anotação de enfermagem deve evitar:","Termos vagos como 'bem' sem descrição","Dados objetivos","Descrever procedimentos","Data e hora","A"],
    ["Médio","Ictérico significa:","Coloração amarelada por hiperbilirrubinemia","Pele azulada","Palidez","Avermelhada","A"],
    ["Médio","Oligúria significa volume:","<400 mL/dia",">2500 mL/dia","Ausente","Normal","A"],
    ["Médio","Exsudato na ferida significa:","Secreção produzida pela ferida","Tecido necrótico","Edema","Crosta","A"],
    ["Médio","Epistaxe significa:","Sangramento nasal","Expectoração com sangue","Vômito com sangue","Sangramento vaginal","A"],
    ["Médio","Afasia significa:","Perda da capacidade de expressão/compreensão","Perda da voz","Dificuldade engolir","Perda movimento","A"],
    ["Médio","Disfagia significa:","Dificuldade para engolir","Dificuldade para falar","Dificuldade para respirar","Dificuldade andar","A"],
    ["Médio","Hemiplegia significa:","Paralisia de um lado do corpo","Paralisia MMII","Paralisia total","Fraqueza muscular","A"],
    ["Médio","Parestesia significa:","Sensação anormal (formigamento)","Paralisia","Dor intensa","Perda consciência","A"],
    ["Médio","A evolução de enfermagem faz parte de qual etapa da SAE?","Avaliação","Histórico","Diagnóstico","Planejamento","A"],
    ["Difícil","Pós-laparotomia: 'dor 7/10 FO, PA 140×90, FC 98, incisão limpa'. SOAP:","S(dor)+O(PA FC)+A(dor controlada)+P(analgésico)","Só S e O","Só A e P","Só P","A"],
    ["Difícil","DPOC: 'falta de ar, FR 28, SpO2 87%, MV diminuído'. SOAP:","S(dispneia)+O(FR SpO2)+A(insuf.respiratória)+P(O2+gasometria)","Só dispneia","Só MV","Só SpO2","A"],
    ["Difícil","Dado INADEQUADO na anotação:","'Paciente parece triste' (subjetivo sem descrição)","Aceitou 75% almoço","Diurese 300 mL em 6h","Deambulou 5 min","A"],
    ["Difícil","Diferença evolução vs anotação:","Anotação=registro pontual; Evolução=sumário diário","São sinônimos","Evolução é médica","Anotação é técnica","A"],
    ["Difícil","Diabetes: 'glicemia 320, confuso, hálito cetônico'. SOAP 'A':","Hiperglicemia suspeita CAD - P: insulina+hidratação","Só hiperglicemia","Só confusão","Só hálito","A"],
    ["Difícil","'Paciente dormiu bem' é inadequado porque:","É vago - deve quantificar horas/qualidade","É verdade","Muito curto","Sem assinatura","A"],
    ["Difícil","AVC: 'afasia global, hemiplegia D, incontinência'. Falta no registro:","SSVV e plano","Nada","Só data","Só assinatura","A"],
    ["Difícil","Cateterismo vesical: 'urina clara 400 mL, sem queixas'. Registro:","Incompleto - falta data/hora/carimbo","Completo","Faltou prescrição","Desnecessário","A"],
    ["Difícil","TCE: Glasgow 11, anisocoria, agitação. Avaliação:","Adequado mas falta plano de reavaliação","Completo","Inadequado","Detalhado demais","A"],
    ["Difícil","Resolução COFEN 429/2012 dispõe sobre:","Registro das ações de enfermagem no prontuário","SAE","Prescrição de medicamentos","Remuneração","A"],
];

$questoesModulo4 = [
    ["Fácil","Quantos certos na administração de medicamentos?","7","5","9","10","A"],
    ["Fácil","O 1º certo da administração é:","Paciente certo","Medicamento certo","Dose certa","Via certa","A"],
    ["Fácil","São vias enterais, EXCETO:","Intramuscular","Oral","Sublingual","Sonda nasogástrica","A"],
    ["Fácil","Absorção sublingual é rápida porque:","Evita metabolismo hepático de primeira passagem","Usa doses maiores","Paciente mastiga","Tem muitas enzimas","A"],
    ["Fácil","VO significa:","Via oral","Via ocular","Via oftálmica","Via orofaringe","A"],
    ["Fácil","Os 7 certos incluem: Paciente, Medicamento, Dose, Via, Horário, Registro e:","Orientação certa","Médico certo","Hospital certo","Leito certo","A"],
    ["Fácil","Via enteral mais comum e segura:","Oral","EV","IM","ID","A"],
    ["Fácil","VO contraindicada em:","Inconscientes ou disfagia","Cefaleia","Febre","Hipertensão","A"],
    ["Fácil","Checagem da medicação deve ser:","Imediatamente após administrar","No final do plantão","Antes de preparar","No dia seguinte","A"],
    ["Fácil","Administração de medicamentos é responsabilidade:","Da equipe de enfermagem","Exclusiva do médico","Só do farmacêutico","Do paciente","A"],
    ["Fácil","SL significa:","Sublingual","Solução","Subcutâneo","Sistema linfático","A"],
    ["Fácil","Via sublingual é para ação:","Rápida","Lenta","Grande volume","Tópica","A"],
    ["Fácil","Liberação prolongada NÃO deve:","Ser partido ou triturado","Ser engolido inteiro","Ser tomado com água","Ser armazenado","A"],
    ["Fácil","Via enteral significa:","Através do trato gastrointestinal","Através da pele","Através dos vasos","Através dos músculos","A"],
    ["Fácil","Via oral é a mais:","Segura, econômica e conveniente","Perigosa","Rápida","Dolorosa","A"],
    ["Fácil","O 'aprazamento' na prescrição médica significa:","Definir os horários de administração","Calcular a dose do medicamento","Preparar o medicamento","Desprezar o medicamento","A"],
    ["Fácil","São horários padronizados na enfermagem, EXCETO:","12/12h (9h e 21h)","8/8h (6h-14h-22h)","6/6h (6h-12h-18h-24h)","4/4h (8h-12h-16h)","D"],
    ["Fácil","A sigla 'SN' (se necessário) na prescrição significa:","Administrar conforme necessidade do paciente","Administrar uma vez ao dia","Administrar sempre","Suspender a medicação","A"],
    ["Fácil","Via inalatória é indicada principalmente para:","Doenças respiratórias (broncodilatadores)","Hipertensão arterial","Infecções bacterianas","Diabetes mellitus","A"],
    ["Fácil","Via retal (VR) é contraindicada em:","Pós-operatório cirurgia retal","Febre alta","Náuseas","Paciente inconsciente","A"],
    ["Médio","Cálculo de gotejamento: prescrito SF 0,9% 500 mL em 8h. Quantas gotas/min?","Aproximadamente 21 gotas/min","42 gotas/min","10 gotas/min","63 gotas/min","A"],
    ["Médio","Dupla checagem de medicação é obrigatória para:","Medicamentos potencialmente perigosos","Todos os medicamentos","Apenas controlados","Apenas injetáveis","A"],
    ["Médio","Medicamentos de alta vigilância (high alert) exigem:","Prescrição destacada e dupla checagem","Apenas receita médica","Apenas registro","Apenas observação","A"],
    ["Médio","Prescrição: dipirona 500 mg VO. Disponível: 1 g (comprimido). Conduta:","Partir comprimido ao meio","Dar comprimido inteiro","Diluir e aspirar metade","Solicitar outro medicamento","A"],
    ["Médio","Interação medicamentosa entre varfarina e AINEs:","Aumenta risco de sangramento","Reduz efeito da varfarina","Não há interação","Aumenta efeito do AINE","A"],
    ["Médio","Via tópica é utilizada para ação:","Local na pele ou mucosas","Sistêmica","Oral","Parenteral","A"],
    ["Difícil","Prescrição: heparina 5.000 UI SC. Disponível: 5.000 UI/0,25 mL. Administrar:","0,25 mL","0,5 mL","1,0 mL","0,1 mL","A"],
    ["Difícil","Paciente em uso de SNG receberá carbamazepina. Cuidado especial:","Forma líquida é preferível; suspensão agita bem antes","Juntar com dieta","Misturar com outros medicamentos","Administrar sem diluir","A"],
    ["Difícil","Sistema de distribuição de medicamentos por dose individualizada:","Fracionado por paciente e horário","Distribuído em massa","Apenas para UTI","Sem controle de horário","A"],
    ["Difícil","Paciente traz receita com: 'Metformina 850 mg VO 2x/dia'. Antes de administrar, o enfermeiro deve verificar:","Se paciente está em jejum para exames","Se é diabético tipo 1 ou 2","Se tem alergia","Se é criança","A"],
    ["Difícil","Conservação de insulina: frasco aberto deve ser:","Mantido em temperatura ambiente (15-30°C) por até 30 dias","Guardado no freezer","Descartado após 7 dias","Mantido na geladeira sempre","A"],
    ["Fácil","A prescrição de medicamentos controlados (portaria 344) exige:","Notificação de Receita (Receita Azul ou Amarela)","Apenas receita comum","Receita verde","Prescrição verbal","A"],
    ["Fácil","Forma farmacêutica líquida via oral:","Xarope, suspensão ou solução","Apenas comprimido","Apenas pílula","Apenas drágea","A"],
    ["Fácil","Antibióticos devem ser administrados:","Em horários fixos para manter nível sérico","Apenas quando o paciente lembrar","Todos juntos pela manhã","Só à noite","A"],
    ["Médio","Cálculo de gotejamento em microgotas: SF 0,9% 250 mL em 6h:","250 × 60 ÷ 360 = ~42 microgotas/min","250 ÷ 6 = ~42 microgotas/min","250 × 20 ÷ 360 = ~14 microgotas/min","250 × 3 = 750 microgotas/min","A"],
    ["Médio","Interação: antiácidos diminuem absorção de:","Tetraciclinas e fluoroquinolonas","Dipirona","Paracetamol","Vitamina C","A"],
    ["Médio","Medicamento termolábil deve ser:","Mantido em geladeira (2-8°C)","Guardado em temperatura ambiente","Congelado","Aquecido antes do uso","A"],
    ["Médio","Via vaginal: forma farmacêutica mais comum:","Óvulos e cremes vaginais","Comprimidos orais","Injeções","Xaropes","A"],
    ["Médio","Prescrição com dose acima do recomendado: conduta do enfermeiro:","Não administrar e questionar o médico","Administrar metade da dose","Administrar e observar","Ignorar e seguir","A"],
    ["Difícil","Compatibilidade medicamentosa na mesma seringa:","Verificar manual de compatibilidade antes de misturar","Pode misturar qualquer medicamento","Nunca misturar nada","Só misturar com SF","A"],
    ["Difícil","Fenitoína EV: cuidado especial:","Administrar em SF, filtrar e não ultrapassar 50 mg/min","Administrar em SG 5%","Injetar rapidamente","Diluir em água destilada","A"],
    ["Difícil","Paciente com sonda nascenteral em uso de Omeprazol: forma correta:","Cápsula não deve ser aberta (perde efeito); usar forma EV","Abrir cápsula e diluir em água","Triturar comprimido","Misturar com a dieta","A"],
    ["Difícil","Quimioterápico oral: cuidado do enfermeiro ao administrar:","Usar EPI (luvas+avental) e descartar em local apropriado","Administrar sem proteção","Só usar luvas","Triturar e diluir","A"],
];

$questoesModulo5 = [
    ["Fácil","Absorção mais rápida:","Endovenosa","Intramuscular","Subcutânea","Intradérmica","A"],
    ["Fácil","Ângulo para injeção intradérmica (ID):","10-15°","45°","90°","180°","A"],
    ["Fácil","Via SC indicada para:","Insulina e heparina","BCG","Grandes volumes EV","Contraste","A"],
    ["Fácil","Volume máximo IM deltoide:","1-2 mL","3 mL","4 mL","5 mL","A"],
    ["Fácil","Ângulo correto para IM:","90°","15°","45°","180°","A"],
    ["Fácil","Local seguro para IM no glúteo:","Quadrante superior externo","Centro do glúteo","Próximo ao nervo ciático","Quadrante inferior interno","A"],
    ["Fácil","A via ID forma pápula. Isso indica:","Técnica correta","Complicação","Erro de aplicação","Infecção","A"],
    ["Fácil","Aspirar antes de injetar IM serve para:","Verificar se atingiu vaso sanguíneo","Misturar o medicamento","Aquecer a agulha","Reduzir dor","A"],
    ["Fácil","A via EV permite:","Grandes volumes e soros","Só pequenos volumes","Só oleosos","Só vacinas","A"],
    ["Fácil","IM vasto lateral preferível em:","Crianças e deltoide pequeno","Idosos obesos","Atletas","Hipertensos","A"],
    ["Fácil","Principal complicação IM:","Abscesso e lesão de nervo","Flebite","Lipodistrofia","Hematoma","A"],
    ["Fácil","Não requer aspiração antes de injetar:","SC (heparina) e ID","IM","Todas requerem","EV","A"],
    ["Fácil","Rodízio de locais na insulina previne:","Lipodistrofia","Hematomas","Flebite","Abscesso","A"],
    ["Fácil","SC absorção mais lenta que IM porque:","Tecido subcutâneo menos vascularizado","Músculo menos vascularizado","Agulha maior","Volume maior","A"],
    ["Fácil","Ação EV é:","Imediata","Lenta","24h","7 dias","A"],
    ["Fácil","A agulha mais utilizada para IM no vasto lateral da criança:","25×7 mm (verde)","13×4,5 (laranja)","30×8 (cinzenta)","40×12 (marrom)","A"],
    ["Fácil","A via parenteral que NÃO rompe a barreira cutânea:","Nenhuma (todas rompem)","ID","SC","Tópica","D"],
    ["Fácil","Seringa de insulina tem capacidade de:","1 mL","3 mL","5 mL","10 mL","A"],
    ["Médio","Prescrito 250 mg, disponível 500 mg/2 mL. Aspirar:","1,0 mL","0,5 mL","1,5 mL","2,0 mL","A"],
    ["Médio","Obeso IMC 42: IM requer:","Agulha mais longa (30×8mm)","Agulha padrão","Via SC","Reduzir dose","A"],
    ["Médio","Técnica Z na IM serve para:","Evitar refluxo do medicamento pelo trajeto","Aumentar dor","Reduzir volume","Acelerar absorção","A"],
    ["Médio","Escolha do cateter EV depende:","Veia+solução+duração","Só preferência","Só medicação","Só paciente","A"],
    ["Médio","Flebite química na EV:","Hiperemia+dor+endurecimento veia","Melhora dor","Diminui calibre","Assintomática","A"],
    ["Médio","Diluição de medicamento IM: penicilina benzatina deve ser:","Reconstituída com água destilada e agitada","Diluída em SF 0,9%","Aquecida antes de usar","Administrada sem diluir","A"],
    ["Médio","Cateter EV periférico (jelco): numeração quanto maior o gauge:","Menor o calibre do cateter","Maior o calibre","Mais longo","Mais curto","A"],
    ["Médio","Infiltração de soroterapia: sinais:","Edema+palidez+frio no local","Hiperemia+calor","Pus+dor intensa","Rash cutâneo","A"],
    ["Difícil","Varfarina INR 4,5 + IM. Conduta:","Contraindicado - risco sangramento","Aplicar normal","Aplicar SC","Reduzir dose","A"],
    ["Difícil","Extravasamento de quimioterápico vesicante:","Parar+aspirar+compressa+comunicar","Continuar","Aumentar velocidade","Massagear","A"],
    ["Difícil","Plaquetas 15.000 + IM:","Contraindicado (risco sangramento)","Aplicar agulha fina","Aplicar SC","Aplicar ID","A"],
    ["Difícil","PCR: sem acesso EV. Via de escolha:","Intraóssea","IM","SC","ID","A"],
    ["Difícil","Pós-mastectomia+esvaziamento axilar D: acesso:","Braço E (contralateral)","Braço D","MMII","Pescoço","A"],
    ["Difícil","Prescrição: Gentamicina 120 mg EV. Disponível: 80 mg/2 mL. Como proceder?","Aspirar 3 mL (120 mg) e administrar em infusão lenta","Aspirar 1,5 mL","Aspirar 4 mL","Diluir em 250 mL SF e infundir","A"],
    ["Fácil","Escala de agulhas: quanto maior o gauge, _____ o calibre:","Menor","Maior","Mais longo","Mais curto","A"],
    ["Fácil","Agulha 13×4,5 (laranja) é usada para:","Via SC (insulina)","Via IM","Via ID","Punção EV","A"],
    ["Fácil","Dispositivo EV de segurança obrigatório:","Cateter com dispositivo de retração da agulha","Seringa comum","Agulha sem dispositivo","Scalp","A"],
    ["Médio","Locais para acesso EV periférico, em ordem de preferência:","Mão → antebraço → fossa antecubital","Fossa antecubital → mão","Pescoço → braço","Perna → pé","A"],
    ["Médio","Sangue para hemocultura: técnica de coleta:","Antissepsia com clorexidina alcoólica, 2-3 amostras de sítios diferentes","Só lavar com água","Usar álcool 70%","Coleta única","A"],
    ["Médio","Heparina SC: local de eleição:","Região abdominal, alternando lados","Braço","Coxa","Glúteo","A"],
    ["Médio","Tipos de solução EV: SF 0,9% é:","Solução isotônica","Hipotônica","Hipertônica","Coloide","A"],
    ["Médio","Reação transfusional: sinais precoces:","Febre+calafrios+urticária+dispneia","Apenas febre","Cefaleia isolada","Hipotensão isolada","A"],
    ["Difícil","Bomba de infusão: alarme de oclusão. Conduta:","Verificar acesso venoso, clicar e desobstruir, reiniciar infusão","Apertar botão para silenciar","Trocar bomba","Aumentar velocidade","A"],
    ["Difícil","Soro glicosado 5% 500 mL EV com KCl 10% 10 mL. Técnica:","Adicionar KCl, homogenizar, etiquetar, infundir em bomba","Injetar KCl direto na veia","Misturar com outras drogas","Infundir sem agitar","A"],
    ["Difícil","Paciente em uso de amiodarona EV: cuidados:","Acesso exclusivo, observar flebite, fotossensibilidade","Pode usar qualquer acesso","Misturar com outras medicações","Infundir rápido","A"],
];

$questoesModulo6 = [
    ["Fácil","Lavagem das mãos: duração mínima de:","20-30 segundos","10 segundos","1 minuto","2 minutos","A"],
    ["Fácil","Sem água: produto indicado:","Álcool 70% gel","Sabão neutro","Clorexidina spray","Água oxigenada","A"],
    ["Fácil","Mudança de decúbito para prevenir UPP a cada:","2 horas","1 hora","4 horas","6 horas","A"],
    ["Fácil","Assepsia é:","Medidas para evitar contaminação","Destruir microorganismos","Limpeza com água","Uso de antibióticos","A"],
    ["Fácil","Antissepsia é:","Remover microorganismos da pele","Esterilizar instrumentos","Lavar mãos","Vacinar","A"],
    ["Fácil","Álcool 70% é classificado como:","Antisséptico/desinfetante","Esterilizante","Detergente","Esporicida","A"],
    ["Fácil","Higiene oral do acamado:","A cada 8h ou conforme","Só quando pedir","1x/dia","Semanal","A"],
    ["Fácil","Banho no leito objetiva:","Higiene+conforto+prevenção de lesões","Só estética","Só conforto","Só reduzir febre","A"],
    ["Fácil","EPI significa:","Equipamento de Proteção Individual","Esquema de Prevenção de Infecção","Equipamento de Proteção Institucional","Estudo do Processo Infeccioso","A"],
    ["Fácil","EPIs básicos de enfermagem:","Luvas+máscara+avental+óculos","Só luvas","Só jaleco","Só máscara","A"],
    ["Fácil","Lavar mãos com água e sabão quando:","Mãos visivelmente sujas","Mãos limpas","Sempre entrar quarto","Só antes cirurgia","A"],
    ["Fácil","Luva de procedimento é para:","Proteger de fluidos corporais","Cirurgias","Feridas abertas","Curativos estéreis","A"],
    ["Fácil","Luvas substituem lavagem das mãos?","Não (têm microfuros)","Sim","Depende","Só estéreis","A"],
    ["Fácil","Higiene do acamado segue ordem:","Cabeça aos pés, áreas limpas primeiro","Pés à cabeça","Sujas primeiro","Só visíveis","A"],
    ["Fácil","Degermação cirúrgica das mãos: duração:","2-5 minutos","20 segundos","10 minutos","15 segundos","A"],
    ["Fácil","A paramentação cirúrgica padrão inclui:","Gorro+máscara+avental estéril+luvas estéreis","Só gorro e luvas","Só avental e luvas","Só máscara e gorro","A"],
    ["Fácil","Resíduo infectante do grupo A deve ser descartado em:","Saco branco leitoso","Saco preto","Saco azul","Saco vermelho","A"],
    ["Fácil","Perfurocortante deve ser descartado em:","Coletor rígido amarelo","Saco comum","Saco branco","Saco azul","A"],
    ["Médio","Luva estéril perfurou na cirurgia:","Trocar por nova estéril","Continuar","Só lavar mãos","Luva procedimento por cima","A"],
    ["Médio","Cateterismo vesical de demora exige:","Campo+sonda+gel estéreis","Só luvas procedimento","Só higiene","Só álcool","A"],
    ["Médio","5 momentos OMS para higiene das mãos:","Antes paciente/antes tarefa asséptica/após fluidos/após paciente/após ambiente","Entrada/saída/refeição/banheiro/contato","Antes e após contato/refeição","Indefinidos","A"],
    ["Médio","Clorexidina age por:","Ação residual prolongada na pele","Oxidação","Coagulação","Aquecimento","A"],
    ["Médio","Esterilização mais comum:","Autoclave (vapor pressão)","Fervura","UV","Álcool","A"],
    ["Médio","Classificação de artigos segundo Spaulding: artigos críticos são os que:","Penetram pele/mucosas estéreis ou sistema vascular","Tocam pele íntegra","Entram em contato com mucosa","Não necessitam esterilização","A"],
    ["Médio","Precaução de gotículas é indicada para:","Influenza e meningite meningocócica","Tuberculose","Sarampo","Escabiose","A"],
    ["Médio","Limpeza terminal da unidade do paciente deve ser feita:","Na alta ou transferência do paciente","1 vez por semana","A cada 24h","Só se sujar","A"],
    ["Difícil","Precaução aérea (tuberculose):","Quarto pressão negativa+N95+máscara paciente se transferir","Só máscara equipe","Só avental","Banho normal","A"],
    ["Difícil","Acidente perfurocortante (agulha contaminada):","Lavar água+sabão+comunicar CCIH+seguir protocolo","Só lavar álcool","Ignorar","Só comunicar","A"],
    ["Difícil","Neutropênico (neutrófilos<500) requer precaução:","Protetora: quarto privativo+sem flores/frutas","Contato","Aérea","Só máscara","A"],
    ["Difícil","Clostridium difficile: lavagem com:","Água e sabão (álcool não elimina esporos)","Álcool 70%","Só água","Não precisa","A"],
    ["Difícil","MRSA (Staph aureus resistente meticilina) precaução:","Contato (luvas+avental)","Padrão","Aérea","Gotículas","A"],
    ["Difícil","RDC ANVISA 222/2018 dispõe sobre:","Gerenciamento de resíduos de serviços de saúde","Higiene das mãos","Precauções de isolamento","Processamento de artigos","A"],
    ["Difícil","Indicador químico de esterilização na autoclave:","Muda de cor após processo validado","Garante 100% de esterilidade","Substitui indicador biológico","É opcional","A"],
    ["Fácil","Precaução padrão: deve ser aplicada:","Para todos os pacientes, independente de diagnóstico","Só para pacientes com doenças infectocontagiosas","Apenas em UTIs","Só em procedimentos cirúrgicos","A"],
    ["Fácil","A degermação cirúrgica das mãos utiliza:","Clorexidina degermante 2% ou PVPI degermante","Álcool 70% sem lavar","Sabão neutro","Água boricada","A"],
    ["Fácil","O jaleco (avental) de uso hospitalar deve ser:","Exclusivo do ambiente de trabalho, trocado diariamente","Usado dentro e fora do hospital","Lavado em casa","Compartilhado entre profissionais","A"],
    ["Médio","Processamento de artigos semicríticos (Spaulding):","Desinfecção de alto nível","Esterilização","Limpeza simples","Desinfecção de baixo nível","A"],
    ["Médio","Indicador biológico de esterilização:","Cultura de esporos bacterianos (Geobacillus stearothermophilus)","Fita crepe","Mudança de cor","Termômetro","A"],
    ["Médio","Isolamento de contato: medidas:","Luvas+avental+quarto privativo ou coorte","Só luvas de procedimento","Só máscara N95","Apenas avental","A"],
    ["Médio","Higienização das mãos antes de calçar luvas estéreis:","Degermação cirúrgica com antisséptico","Lavagem simples com água","Só álcool em gel","Não precisa lavar","A"],
    ["Médio","Óculos de proteção devem ser usados:","Em risco de respingos de sangue/secreções","Só em cirurgias","Apenas em UTIs","Só durante curativos","A"],
    ["Difícil","Paciente com ferimento contaminado: tipo de luva:","Luva estéril para procedimento","Luva de procedimento","Luva de borracha","Sem luva","A"],
    ["Difícil","Álcool 70% NÃO é esporicida. Isso significa:","Não elimina esporos bacterianos","Elimina todos os microorganismos","É igual a esterilização","Não precisa de contato","A"],
    ["Difícil","Desinfecção de alto nível: indicada para:","Artigos semicríticos (endoscópios, cânulas)","Instrumentos críticos","Pele íntegra","Ambientes hospitalares","A"],
];

$questoesModulo7 = [
    ["Fácil","Objetivo principal do curativo:","Proteger e promover cicatrização","Embelezar a ferida","Só estancar sangue","Só medicar","A"],
    ["Fácil","Ferida aguda caracteriza-se por:","Cicatrizar em <30 dias","Nunca cicatrizar","Sempre infeccionar","Precisar de cirurgia","A"],
    ["Fácil","Ferida crônica tem:","Tempo >30 dias","Cicatrização rápida","Só origem traumática","Só em diabéticos","A"],
    ["Fácil","UPP é causada por:","Pressão prolongada em proeminências ósseas","Infecção bacteriana","Queimadura","Alergia","A"],
    ["Fácil","Desbridamento significa:","Remover tecido necrótico","Hidratar a ferida","Cobrir a ferida","Medicar","A"],
    ["Fácil","Alginato de cálcio é para feridas:","Com exsudato moderado a intenso","Secas","Infectadas","Com necrose seca","A"],
    ["Fácil","Carvão ativado em curativos serve para:","Controlar odor e absorver exsudato","Hidratar a pele","Acelerar cicatrização","Anestesiar","A"],
    ["Fácil","Escala de Braden avalia:","Risco de úlcera por pressão","Nível de consciência","Dor do paciente","Gravidade da ferida","A"],
    ["Fácil","Sinais de infecção na ferida:","Eritema+calor+pus+odor","Tecido de granulação","Epitelização","Diminuição do exsudato","A"],
    ["Fácil","Hidrogel é indicado para feridas:","Secas ou necrose (desbridamento autolítico)","Com exsudato abundante","Infectadas com pus","Queimadura 3° grau","A"],
    ["Fácil","Tecido de granulação saudável é:","Vermelho vivo e sangra fácil","Preto","Amarelo","Purulento","A"],
    ["Fácil","Tecido necrótico tem cor:","Preta ou amarronzada","Vermelha","Rósea","Branca","A"],
    ["Fácil","UPP estágio 1:","Eritema não branqueável, pele íntegra","Perda total da pele","Exposição óssea","Bolha","A"],
    ["Fácil","UPP estágio 2:","Perda parcial da pele com bolha","Eritema","Exposição subcutâneo","Osso exposto","A"],
    ["Fácil","UPP estágio 3:","Perda total da pele com exposição subcutânea","Pele íntegra","Bolha","Osso exposto","A"],
    ["Fácil","UPP estágio 4:","Perda total com exposição de músculo/osso","Perda parcial da pele","Eritema","Bolha","A"],
    ["Fácil","Queimadura de 1° grau atinge:","Epiderme","Derme","Hipoderme","Músculo","A"],
    ["Fácil","Queimadura de 2° grau forma:","Bolhas (flictenas)","Necrose profunda","Escara","Crosta","A"],
    ["Médio","UPP em sacro + Braden <12:","Medidas preventivas intensivas","Só observar","Só colchão","Ignorar","A"],
    ["Médio","Fator que mais retarda cicatrização:","Infecção e desnutrição","Idade","Sexo","Altura","A"],
    ["Médio","Pé diabético neuropático requer:","Desbridamento+alívio pressão+controle glicêmico","Curativo simples","Amputação","Só ATB","A"],
    ["Médio","Curativo com alginato forma gel:","Ação hemostática e absorção","Sinal de infecção","Necrose","Alergia","A"],
    ["Médio","Ferida com exsudato purulento:","Curativo com antimicrobiano tópico","Só SF","Só cobrir","Ignorar","A"],
    ["Médio","Sulfadiazina de prata 1% é indicada para:","Queimaduras de 2° grau","Feridas secas","UPP estágio 1","Feridas com necrose seca","A"],
    ["Médio","Papaina é uma enzima que atua:","Desbridamento químico de tecido necrótico","Hidratação da ferida","Controle de odor","Hemostasia","A"],
    ["Médio","Deiscência de ferida cirúrgica significa:","Abertura dos pontos e separação das bordas","Infecção local","Hematoma subcutâneo","Cicatrização normal","A"],
    ["Difícil","Pé diabético neuropático com úlcera infectada + osteomielite. Conduta:","Desbridamento+ATB sistêmico+alívio pressão+avaliação vascular","Só curativo","Só ATB oral","Amputação imediata","A"],
    ["Difícil","Ferida oncológica: odor fétido, exsudato abundante. Cobertura:","Carvão ativado + alginato","Hidrogel","SF 0,9%","Papaina","A"],
    ["Difícil","UPP estágio 4 com exposição óssea + infecção:","Desbridamento cirúrgico + ATB + curativo especializado","Só curativo diário","Só ATB sistêmico","Só pomada","A"],
    ["Difícil","Terapia a vácuo é indicada para:","Feridas complexas para acelerar granulação","Feridas secas","Feridas infectadas","Feridas cirúrgicas recentes","A"],
    ["Difícil","Avaliação de ferida: o que deve ser registrado?","Local+tamanho+profundidade+tecido+exsudato+bordas","Só tamanho","Só local","Só odor","A"],
    ["Difícil","Queimadura 3° grau: característica principal:","Pele carbonácea ou branca perolada, indolor","Dor intensa","Bolhas extensas","Hiperemia local","A"],
    ["Difícil","Curativo compressivo em úlcera venosa serve para:","Reduzir edema e melhorar retorno venoso","Imobilizar o membro","Aquecer o local","Proteger de trauma","A"],
    ["Fácil","Ferida cirúrgica limpa: tempo esperado de cicatrização:","7-14 dias","30 dias","2 meses","6 meses","A"],
    ["Fácil","Princípio básico da cicatrização:","Ferida úmida cicatriza mais rápido que seca","Ferida deve ficar seca","Ferida precisa de ar","Crosta acelera cicatrização","A"],
    ["Fácil","Cobertura de espuma de poliuretano (curativo foam) serve para:","Absorção de exsudato e conforto","Feridas secas","Feridas com necrose","Queimadura 3° grau","A"],
    ["Fácil","Colagenase é uma enzima que:","Degrada colágeno, desbridando tecido necrótico","Hidrata a ferida","Absorve exsudato","Controla odor","A"],
    ["Médio","Ferida com tecido de granulação hipertrófico: conduta:","Avaliar necessidade de cauterização com nitrato de prata","Continuar curativo normal","Aplicar hidrogel","Usar alginato","A"],
    ["Médio","Lesão por fricção (skin tear): classificação:","Tipo 1 (sem perda), 2 (perda parcial), 3 (perda total)","Estágio 1 a 4","Grau A, B, C","Somente uma classificação","A"],
    ["Médio","Pé diabético: classificação de Wagner:","Grau 0 (risco) a 5 (gangrena extensa)","Estágio 1 a 4","Tipo A, B, C","Grau leve a grave","A"],
    ["Médio","Fator de crescimento em curativos: indicado para:","Feridas crônicas sem cicatrização","Feridas agudas","Queimaduras recentes","Feridas infectadas","A"],
    ["Médio","Hidrocolóide: indicação principal:","UPP estágios 1 e 2, com exsudato leve","Feridas com necrose","Feridas infectadas","Queimaduras 3° grau","A"],
    ["Difícil","Queimadura por eletricidade: risco principal:","Lesões internas profundas + arritmias cardíacas","Lesão apenas superficial","Dor intensa localizada","Infecção imediata","A"],
    ["Difícil","Ferida com exposição de tendão: cobertura indicada:","Curativo com alginato+placa de prata ou hidrogel","Hidrocolóide","Espuma simples","Filme transparente","A"],
    ["Difícil","Paciente queimado: regra dos 9 para superfície corporal:","Cada braço 9%, tronco anterior 18%, perna 18%","Braço 18%, perna 9%","Tronco 36%","Cabeça 18%","A"],
];

$questoesModulo8 = [
    ["Fácil","Oxigenoterapia é indicada para SpO2 abaixo de:","90%","95%","85%","80%","A"],
    ["Fácil","Dispositivo mais comum para oxigenoterapia de baixo fluxo:","Cateter nasal (óculos nasal)","Máscara de Venturi","Máscara com reservatório","Tenda facial","A"],
    ["Fácil","Sonda nasogástrica (SNG) serve para:","Descompressão gástrica e medicamentos","Apenas alimentar","Apenas drenar","Apenas lavar estômago","A"],
    ["Fácil","Sonda enteral (SNE) tem ponta no:","Intestino delgado","Estômago","Intestino grosso","Esôfago","A"],
    ["Fácil","SpO2 significa:","Saturação periférica de oxigênio","Pressão sistólica","Frequência cardíaca","Pressão venosa","A"],
    ["Fácil","Valor normal de SpO2 em adulto saudável:","95-100%","85-90%","80-85%","70-75%","A"],
    ["Fácil","Antes da dieta por SNE, verificar:","Posicionamento e resíduo gástrico","Temperatura da dieta","Glicemia capilar","Pressão arterial","A"],
    ["Fácil","Cateterismo vesical de alívio: remove a sonda:","Imediatamente após esvaziar a bexiga","Após 24h","Após 7 dias","Após 1 semana","A"],
    ["Fácil","Sonda de Foley é usada para:","Cateterismo vesical de demora","Oxigenoterapia","Sondagem gástrica","Drenagem torácica","A"],
    ["Fácil","Principal complicação do cateterismo vesical de demora:","Infecção do trato urinário","Dor local","Hematúria","Incontinência","A"],
    ["Fácil","Cabeceira do paciente com SNE deve ser mantida:","Elevada 30-45° durante e após dieta","Abaixada","Plana","Trendelenburg","A"],
    ["Fácil","Sinais de obstrução de SNG:","Impossibilidade de aspirar ou administrar líquidos","Saída fácil de conteúdo","Dor abdominal leve","Náusea passageira","A"],
    ["Fácil","O volume máximo recomendado para dieta por SNE por vez:","300-500 mL","1000 mL","50 mL","800 mL","A"],
    ["Fácil","Máscara de Venturi é classificada como sistema de:","Alto fluxo com FiO2 controlada","Baixo fluxo","Reservatório","Não reinalante","A"],
    ["Médio","Máscara de Venturi oferece:","Concentração precisa e controlada de O2","Alto fluxo sem controle","Baixo custo","Maior conforto","A"],
    ["Médio","Paciente com DPOC deve receber O2 controlado porque:","Alto O2 pode abolir drive respiratório dependente de hipóxia","Tem mais tolerância","Não precisa de O2","Precisa de O2 puro","A"],
    ["Médio","Volume de dieta por SNE deve ser administrado:","Gravidade ou bomba de infusão, em decúbito elevado","Rápido em bolus","Paciente deitado","Sem controle de volume","A"],
    ["Médio","Aspiração de vias aéreas em paciente intubado: pressão máxima de vácuo:","120-150 mmHg","200-250 mmHg","80-100 mmHg","300 mmHg","A"],
    ["Médio","Cateterismo vesical feminino: sequência correta:","Higiene→abrir campo→luvas estéreis→introduzir sonda","Luvas→higiene→sonda","Sonda→higiene→campo","Luvas→campo→higiene","A"],
    ["Médio","Cuidados com ostomia intestinal: o leito periestoma deve ser:","Limpo, seco e com barreira protetora","Coberto com gaze seca","Lavado com água oxigenada","Deixado aberto sem cobertura","A"],
    ["Difícil","Paciente em VM: parâmetro para desmame:","Pressão suporte (PSV) reduzida progressivamente","FiO2 100%","Volume corrente 800 mL","PEEP 20","A"],
    ["Difícil","Sangramento por SNG: conduta inicial:","Avaliar sinais vitais+comunicar médico+suspender dieta","Aumentar dieta","Clampear sonda","Ignorar","A"],
    ["Difícil","Paciente com traqueostomia: aspiração deve ser:","Estéril, técnica asséptica, máximo 15 segundos","Com luva de procedimento","Sem luva","Sem limite de tempo","A"],
    ["Difícil","Derrame pleural com dreno de tórax: cuidados:","Manter selo d'água, clampear só para troca, radiografia","Clampear sempre","Selar a drenagem","Colocar aspiração contínua","A"],
    ["Difícil","Gasometria arterial: parâmetro de insuficiência respiratória:","PaO2 <60 mmHg ou PaCO2 >50 mmHg","PaO2 <90 mmHg","PaCO2 <35 mmHg","pH >7,45","A"],
    ["Difícil","Paciente traqueostomado: sinais de obstrução da cânula:","Dispneia súbita+tiragem+SpO2 caindo+impossibilidade de passar aspirador","Febre alta","Tosse seca","Secreção amarelada","A"],
    ["Difícil","Dreno de tórax com vazamento de ar no selo d'água:","Avaliar se há fuga no sistema+não clampear+comunicar médico","Clampear imediatamente","Tirar o dreno","Aumentar aspiração","A"],
    ["Difícil","Paracentese: cuidados de enfermagem no preparo:","Solicitar esvaziamento vesical+aferir sinais vitais","Oferecer refeição pesada","Posicionar em decúbito ventral","Não precisa de preparo","A"],
    ["Médio","Punção venosa periférica: torniquete deve permanecer no máximo:","1-2 minutos","5 minutos","30 segundos","10 minutos","A"],
    ["Fácil","A válvula de Heimlich é usada em:","Dreno torácico para pneumotórax","Traqueostomia","Oxigenoterapia","Cateterismo","A"],
    ["Fácil","Objetivo da oxigenoterapia:","Corrigir hipoxemia mantendo SpO2 >90%","Aumentar FC","Reduzir PA",",Curar pneumonia","A"],
    ["Fácil","Dispositivo de O2 de alto fluxo: indicação:","Pacientes que precisam de FiO2 precisa e constante","Pacientes estáveis","Pacientes com DPOC","Apenas em emergência","A"],
    ["Fácil","Sonda de aspiração: calibre deve ser:","Metade do diâmetro da cânula traqueal","Mesmo diâmetro da cânula","Maior que a cânula","Menor possível","A"],
    ["Médio",",Paciente em VM: parâmetros de alarme:","Pressão alta, volume minuto baixo, apneia","Apenas frequência","Apenas volume","Apenas FiO2","A"],
    ["Médio",",Cuidado com paciente em uso de cateter nasal de O2:","Trocar a cada 24h e inspecionar narinas","Trocar semanalmente","Manter fixo sem limpar","Usar apenas 1x","A"],
    ["Médio","Coleta de gasometria arterial: cuidados:","Avaliar circulação colateral (teste de Allen)","Escolher veia calibrosa","Usar agulha 13×4,5","Massagear o local","A"],
    ["Médio","Dieta por SNE: posição do paciente:","Sentado ou cabeceira 30-45°","Deitado","Decúbito dorsal","Decúbito ventral","A"],
    ["Difícil","Extubação acidental: conduta do enfermeiro:","Avaliar esforço respiratório+SpO2+comunicar médico","Reintubar imediatamente","Sedar paciente","Aumentar O2","A"],
    ["Difícil","Dreno torácico com vazamento: conduta:","Avaliar conexões, nunca clampear sem ordem médica","Clampear o dreno","Retirar o dreno","Aumentar aspiração","A"],
    ["Difícil","Cânula de traqueostomia: cuidados diários:","Limpeza com SF+curativo estéril+avaliação da pele","Apenas aspirar secreção","Limpar com água","Trocar 1x/semana","A"],
];

$questoesModulo9 = [
    ["Fácil","PA 120×80 mmHg, FC 72 bpm, FR 18 irpm, Tax 36,5°C são valores:","Dentro da normalidade","Acima do normal","Abaixo do normal","Indicativos de sepse","A"],
    ["Fácil","Crioterapia é tratamento por:","Frio","Calor","Laser","Ultrassom","A"],
    ["Fácil","Termoterapia é tratamento por:","Calor","Frio","Radiação","Eletricidade","A"],
    ["Fácil","Compressa fria é indicada para:","Processo inflamatório agudo e edema","Contratura muscular","Hipotermia","Tremores","A"],
    ["Fácil","Compressa quente é indicada para:","Alívio de dor muscular e abscesso","Hemorragia ativa","Febre alta","Edema agudo","A"],
    ["Fácil","Coleta de sangue em jejum requer:","Jejum de 8-12h conforme exame","Café da manhã leve","Exercício leve","Refeição normal","A"],
    ["Fácil","Para aferir PA, o manguito deve:","Cobrir 40% da circunferência do braço","Cobrir todo o braço","Ser colocado sobre a roupa","Ficar insuflado 5 min","A"],
    ["Fácil","Glicemia capilar deve ser coletada:","Lateral da ponta do dedo","Centro da ponta do dedo","Palma da mão","Antebraço","A"],
    ["Fácil","Aferição de temperatura axilar: duração:","3-5 minutos","30 segundos","1 minuto","10 minutos","A"],
    ["Fácil","Sinais vitais incluem:","PA, FC, FR, Tax","PA e FC","FC e FR","Só PA","A"],
    ["Fácil","Valor normal de glicemia em jejum para adulto:","70-99 mg/dL","100-126 mg/dL","130-150 mg/dL","50-70 mg/dL","A"],
    ["Fácil","Oximetria de pulso: local mais comum para colocação do sensor:","Ponta do dedo indicador","Lóbulo da orelha","Testa","Hálux","A"],
    ["Fácil","Frequência cardíaca normal em adulto em repouso:","60-100 bpm","40-60 bpm","100-140 bpm","50-70 bpm","A"],
    ["Médio","Crioterapia nas primeiras 24-48h após entorse serve para:","Reduzir edema e inflamação","Aquecer o local","Relaxar o músculo","Aumentar fluxo sanguíneo","A"],
    ["Médio","Termoterapia é contraindicada em:","Neoplasia suspeita ou hemorragia ativa","Dor muscular","Contratura","Processo inflamatório crônico","A"],
    ["Médio","Urocultura deve ser colhida por:","Jato médio com higiene e frasco estéril","Urina de 24h","Urina matinal sem higiene","Qualquer horário","A"],
    ["Médio","Coleta de hemocultura: número recomendado:","2 a 3 amostras de sítios diferentes","1 amostra","4 amostras","5 amostras","A"],
    ["Médio","Crioterapia por mais de 30 min pode causar:","Queimadura por frio e lesão tecidual","Vasodilatação","Analgesia duradoura","Aumento do fluxo sanguíneo","A"],
    ["Médio","Eletrocardiograma (ECG): derivação padrão DII é:","Braço D (+) e perna E (-)","Braço E (+) e perna D (-)","Braço D (+) e braço E (-)","Perna D (+) e perna E (-)","A"],
    ["Médio","Valor normal de potássio (K+) sérico:","3,5-5,5 mEq/L","2,0-3,0 mEq/L","6,0-8,0 mEq/L","1,0-2,5 mEq/L","A"],
    ["Difícil","Paciente com INR 5,8 (alvo 2-3) em varfarina requer:","Suspender, avaliar sangramentos e preparar vitamina K","Manter medicação","Aumentar dose","Repetir exame em 7 dias","A"],
    ["Difícil","Glicemia capilar 45 mg/dL em paciente consciente:","Administrar glicose oral + comunicar médico","Iniciar insulina","Repetir em 30 min","Aguardar evolução","A"],
    ["Difícil","PA 180×110 em paciente assintomático no PS:","Monitorar + comunicar médico + avaliar lesão órgão-alvo","Iniciar anti-hipertensivo imediato","Só repouso","Alta hospitalar","A"],
    ["Difícil","Febre 39,5°C pós-operatório imediato: principal causa:","Atelectasia (primeiras 48h)","Infecção da ferida","Infecção urinária","Sepse","A"],
    ["Difícil","Cultura de ponta de cateter: indicação:","Suspeita de infecção relacionada ao CVC","Todos os pacientes com CVC","Rotina semanal","Só se positiva","A"],
    ["Difícil","Gasometria arterial normal: parâmetros:","pH 7,35-7,45 / PaCO2 35-45 / HCO3 22-26","pH 7,20-7,30 / PaCO2 50-60","pH 7,50-7,60 / PaCO2 20-30","pH 6,8-7,2 / PaCO2 60-70","A"],
    ["Difícil","Cetonúria em paciente diabético indica:","Metabolismo de gorduras - risco de cetoacidose","Bom controle glicêmico","Hiperpotassemia","Infecção urinária","A"],
    ["Difícil","Pressão intracraniana (PIC) normal em adulto:","5-15 mmHg","20-30 mmHg","1-5 mmHg","30-40 mmHg","A"],
    ["Fácil","O pulso radial é palpado com os dedos:","Indicador e médio","Polegar","Mínimo","Todos os dedos","A"],
    ["Médio","Hipotensão postural: alteração esperada:","Queda PA sistólica ≥20 mmHg ao levantar","Aumento FC ao deitar","Normal em jovens","Sempre patológica","A"],
    ["Fácil","PA normal para adulto segundo OMS:","<120/<80 mmHg","<140/<90 mmHg","<130/<85 mmHg","<150/<100 mmHg","B"],
    ["Fácil","FC normal para adulto em repouso:","60-100 bpm","40-60 bpm","100-140 bpm","50-70 bpm","A"],
    ["Fácil","Frequência respiratória normal adulto:","12-20 irpm","20-30 irpm","8-12 irpm","30-40 irpm","A"],
    ["Fácil","Temperatura axilar normal:","35,5-37,0°C","37,5-38,5°C","34,0-35,0°C","38,0-39,0°C","A"],
    ["Médio","Aferição PA: técnica palpatória serve para:","Estimar PAS antes de auscultar","Substituir ausculta","Aferir PAD","Avaliar FC","A"],
    ["Médio","Coleta de ureia e creatinina: jejum necessário?","Não obrigatório","Jejum de 12h","Jejum de 8h","Apenas água","A"],
    ["Médio","Febre: ponto de ajuste hipotalâmico:","Termostato corporal elevado por pirogênios","Aumento da produção de calor","Redução da perda de calor","Infecção local","A"],
    ["Médio","Hipotermia: temperatura abaixo de:","35°C","36°C","36,5°C","34°C","A"],
    ["Médio","Anti-hipertensivo VO: horário ideal:","Conforme prescrição, geralmente 1-2x/dia","Qualquer horário","Só à noite","Se PA estiver alta","A"],
    ["Difícil","Sepse: critérios de qSOFA:","FR≥22 + alteração mental + PAS≤100","FC>120+PA<90","Febre+taquicardia","Leucocitose+PCR alto","A"],
    ["Difícil","PCR: ritmo chocável:","FV (fibrilação ventricular) e TV sem pulso","Assistolia","AESP","Bradicardia sinusal","A"],
    ["Difícil","Paciente com tromboembolismo pulmonar: sinal clássico:","Dispneia súbita+dor torácica+hemoptise","Febre alta","Cefaleia intensa","Dor abdominal","A"],
    ["Difícil","Infarto agudo do miocárdio: marcador precoce:","Troponina (aumenta em 2-4h)","CK-MB","Mioglobina","CPK total","A"],
];

$questoesModulo10 = [
    ["Fácil","A admissão hospitalar inclui:","Acolhimento, avaliação e orientações","Apenas preencher papéis","Apenas encaminhar ao leito","Apenas aferir sinais","A"],
    ["Fácil","A alta hospitalar deve ser planejada:","Desde a admissão, progressivamente","No momento da alta","Apenas para cirúrgicos","Pelo médico apenas","A"],
    ["Fácil","A contenção física deve ser:","Último recurso com indicação e registro","Rotina para idosos","Usada em todos confusos","Sem necessidade de registro","A"],
    ["Fácil","Processo pós-morte (tanatologia) inclui:","Higiene, identificação e acolhimento à família","Apenas remover corpo","Apenas lavar corpo","Apenas declaração de óbito","A"],
    ["Fácil","Conteúdo mecânica exige prescrição médica e:","Avaliação contínua e registro sistemático a cada 2h","Pode ser por qualquer profissional","Apenas supervisão familiar","Aplicação sem registro","A"],
    ["Fácil","Preparo do corpo pós-morte deve ser:","Higiene, curativos, identificação e dignidade","Apenas cobrir com lençol","Apenas vestir o paciente","Sem identificação","A"],
    ["Fácil","Transferência entre setores exige:","Comunicação verbal e escrita das condições e cuidados","Apenas enviar prontuário","Apenas comunicação verbal","Apenas encaminhamento médico","A"],
    ["Fácil","A alta a pedido (paciente solicita) exige:","Termo de responsabilidade assinado e orientações registradas","Proibido por lei","Apenas liberar paciente","Apenas avisar família","A"],
    ["Fácil","Na admissão, o enfermeiro deve:","Avaliar e acolher o paciente e família","Só preencher papéis","Só encaminhar ao leito","Só aferir sinais vitais","A"],
    ["Fácil","A contenção de pacientes deve ser revista:","A cada 2 horas","A cada 12 horas","A cada 24 horas","Semanalmente","A"],
    ["Médio","Paciente sob contenção por 4h deve ser avaliado:","A cada 2h liberando para ver pele e circulação","Apenas no final do plantão","Sem reavaliação","Semanalmente","A"],
    ["Médio","Paciente terminal recebe alta a pedido. O enfermeiro deve:","Orientar cuidados, oferecer suporte e registrar","Recusar alta","Transferir para UTI","Liberar sem orientações","A"],
    ["Médio","Família solicita ficar com corpo após óbito. Conduta:","Permitir com orientações e acompanhamento","Negar veementemente","Ignorar pedido","Liberar sem preparo","A"],
    ["Médio","Paciente psiquiátrico em surto requer:","Desescalada verbal; se necessário contenção com equipe e prescrição","Conter à força imediatamente","Sedação e contenção sozinho","Isolar sem supervisão","A"],
    ["Médio","Admissão de vítima de violência: conduta:","Acolher, documentar, notificar e oferecer suporte","Apenas tratar lesões","Questionar agressor","Ignorar sinais","A"],
    ["Difícil","Conteúdo de paciente agitado por 8h: complicação temida:","Lesão por pressão no local de contenção","Hipoglicemia","Hipertensão","Cefaleia","A"],
    ["Difícil","Processo de alta de paciente oncológico paliativo:","Plano de cuidados paliativos domiciliares + suporte emocional","Alta simples","Transferência para UTI","Encaminhamento para cirurgia","A"],
    ["Difícil","Morte encefálica: protocolo exige:","Dois exames clínicos + exame complementar","Apenas um exame clínico","Só tomografia","Só eletroencefalograma","A"],
    ["Difícil","Admissão de paciente em isolamento por doença infectocontagiosa:","Precaução específica + orientações + visitas restritas","Isolamento sem orientação","Visitantes liberados","Só máscara no paciente","A"],
    ["Difícil","Alta de paciente traqueostomado: orientações essenciais:","Cuidados com estoma+aspiração+aspiração+emergências","Só curativo","Só medicação","Sem orientações","A"],
    ["Fácil","O acolhimento com classificação de risco é um dispositivo:","Da Política Nacional de Humanização (PNH)","Do Código de Ética","Da Resolução COFEN","Do SUS apenas","A"],
    ["Fácil","O direito do paciente a acompanhante é garantido:","Pelo SUS (Lei 8.080/90) e Estatuto do Idoso","Apenas para crianças","Apenas para idosos","Não é direito","A"],
    ["Fácil","São direitos do paciente hospitalizado:","Privacidade, informação e consentimento","Apenas receber visitas","Apenas alimentação","Apenas medicação","A"],
    ["Fácil","A visita multidisciplinar ao paciente deve ser:","Coordenada, com respeito à privacidade","Restrita ao médico","Apenas para idosos","Sem horário fixo","A"],
    ["Médio","Alta a pedido: documentação necessária:","Termo de Responsabilidade assinado + orientações registradas","Apenas assinatura do paciente","Apenas comunicação verbal","Autorização médica","A"],
    ["Médio","Comunicação de óbito: o enfermeiro pode:","Constatado o óbito, registrar e comunicar equipe e família","Declarar o óbito no atestado","Remover o corpo sem registro","Aguardar o médico para tudo","A"],
    ["Médio","Transferência de paciente entre hospitais: o enfermeiro deve:","Relatório de enfermagem + medicações + equipamentos","Apenas encaminhar prontuário","Apenas comunicar","Sem documentação","A"],
    ["Médio","Cuidados paliativos na terminalidade: prioridade:","Conforto, alívio da dor, suporte emocional e espiritual","Prolongar vida a qualquer custo","Realizar todos os exames","Manter internação","A"],
    ["Médio","O paciente terminal tem direito:","A cuidados paliativos, informação e dignidade","Apenas a receber visitas","A ser mantido sedado","A alta hospitalar imediata","A"],
    ["Difícil","Protocolo de morte encefálica exige:","Dois exames clínicos + teste de apneia + exame complementar","Apenas um exame clínico","Apenas eletroencefalograma","Só tomografia","A"],
    ["Difícil","Cuidados de enfermagem na morte encefálica (doador):","Manter parâmetros hemodinâmicos para viabilidade dos órgãos","Suspender todas as medicações","Extubar imediatamente","Transferir para enfermaria","A"],
    ["Difícil","Doação de órgãos: quem pode ser doador?","Qualquer pessoa com morte encefálica e autorização familiar","Apenas quem assinou documento em vida","Apenas jovens","Apenas pacientes cadastrados","A"],
    ["Difícil","Consentimento familiar para doação: conduta do enfermeiro:","Apoiar a família, esclarecer dúvidas e comunicar à equipe de transplante","Convencer a família a doar","Omitir informações","Só preencher documentos","A"],
    ["Difícil","Sedação paliativa em cuidados paliativos: objetivo:","Aliviar sintomas refratários com redução proporcional da consciência","Induzir coma","Acelerar o óbito","Prolongar a vida","A"],
    ["Fácil","São princípios do SUS, EXCETO:","Integralidade","Equidade","Lucratividade","Universalidade","C"],
];
